name: Chess Engine CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies (without package installation)
        run: poetry install --no-root

      - name: Run pytest tests
        run: poetry run pytest tests/ --exitfirst --verbose
